### ISSUE TITLE
Not found video directory

### ISSUE THREAD

**Issue by z4n1t015** [bluesky-dev12/MAD-x-VP6-x-MPC-x-MPV-x-WMV-Compiler#1]
After converting MP4 to VP6 or MPC, i go to release past and i not found the archive ):

**Comment by bluesky-dev12** [comment]
Fixed on 3.0 (Tested by z4n1t015)

**Comment by bluesky-dev12** [comment]
Fixed on release 3.0. (Tested by z4n1t015)
